name: Terratest

on:
  push:

jobs:
  terratest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v2  
        with:
          node-version: '18'

      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.2"
          terraform_wrapper: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install awscli 

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7' # The Go version to download (if necessary) and use.

      - run: go version
      
 #     - name: Configure AWS credentials
 #       uses: aws-actions/configure-aws-credentials@v4
 #       with:
 #         role-to-assume: ${{ env.AWS_ROLE }}
 #         role-session-name: ${{ env.AWS_SESSION }}
 #         aws-region: ${{ env.AWS_REGION }}
 #         audience: sts.amazonaws.com

      - name: Download Go Modules
        working-directory: terratest
        run: go mod download

      - name: Run Go Tests
        working-directory: terratest
        run: go test -v -timeout 60m -tags=unit